export const START_FETCHING_PARTICIPANTS = "redux/participants/START_FETCHING_PARTICIPANTS",
  SUCCESS_FETCHING_PARTICIPANTS = "redux/participants/SUCCESS_FETCHING_PARTICIPANTS",
  ERROR_FETCHING_PARTICIPANTS = "redux/participants/ERROR_FETCHING_PARTICIPANTS",
  SET_KEYWORD_PARTICIPANTS = "redux/participants/SET_KEYWORD_PARTICIPANTS";
