export const START_FETCHING_TRANSACTIONS = "redux/transactions/START_FETCHING_TRANSACTIONS",
  SUCCESS_FETCHING_TRANSACTIONS = "redux/transactions/SUCCESS_FETCHING_TRANSACTIONS",
  ERROR_FETCHING_TRANSACTIONS = "redux/transactions/ERROR_FETCHING_TRANSACTIONS",
  SET_EVENT = "redux/transactions/SET_EVENT",
  SET_KEYWORD_TRANSACTIONS = "redux/transactions/SET_KEYWORD_TRANSACTIONS",
  SET_DATE = "redux/transactions/SET_DATE",
  SET_PAGE = "redux/transactions/SET_PAGE";
