export const START_FETCHING_EVENTS = "redux/events/START_FETCHING_EVENTS",
  SUCCESS_FETCHING_EVENTS = "redux/events/SUCCESS_FETCHING_EVENTS",
  ERROR_FETCHING_EVENTS = "redux/events/ERROR_FETCHING_EVENTS",
  SET_KEYWORD_EVENTS = "redux/events/SET_KEYWORD_EVENTS";
