export const START_FETCHING_SPEAKERS = "redux/speakers/START_FETCHING_SPEAKERS",
  SUCCESS_FETCHING_SPEAKERS = "redux/speakers/SUCCESS_FETCHING_SPEAKERS",
  ERROR_FETCHING_SPEAKERS = "redux/speakers/ERROR_FETCHING_SPEAKERS",
  SET_KEYWORD_SPEAKERS = "redux/speakers/SET_KEYWORD_SPEAKERS";
