// List Categories
export const START_FETCHING_LISTS_CATEGORIES = "redux/lists/START_FETCHING_LISTS_CATEGORIES",
  SUCCESS_FETCHING_LISTS_CATEGORIES = "redux/lists/SUCCESS_FETCHING_LISTS_CATEGORIES",
  ERROR_FETCHING_LISTS_CATEGORIES = "redux/lists/ERROR_FETCHING_LISTS_CATEGORIES";

// List Speakers
export const START_FETCHING_LISTS_SPEAKERS = "redux/lists/START_FETCHING_LISTS_SPEAKERS",
  SUCCESS_FETCHING_LISTS_SPEAKERS = "redux/lists/SUCCESS_FETCHING_LISTS_SPEAKERS",
  ERROR_FETCHING_LISTS_SPEAKERS = "redux/lists/ERROR_FETCHING_LISTS_SPEAKERS";

// List Event
export const START_FETCHING_LISTS_EVENTS = "redux/lists/START_FETCHING_LISTS_EVENTS",
  SUCCESS_FETCHING_LISTS_EVENTS = "redux/lists/SUCCESS_FETCHING_LISTS_EVENTS",
  ERROR_FETCHING_LISTS_EVENTS = "redux/lists/ERROR_FETCHING_LISTS_EVENTS";
