export const START_FETCH_CATEGORIES = "redux/categories/START_FETCH_CATEGORIES";
export const SUCCESS_FETCH_CATEGORIES = "redux/categories/SUCCESS_FETCH_CATEGORIES";
export const ERROR_FETCH_CATEGORIES = "redux/categories/ERROR_FETCH_CATEGORIES";
