export const START_FETCH_CATEGORIES = "redux/auth/START_FETCH_CATEGORIES";
export const SUCCESS_FETCH_CATEGORIES = "redux/auth/SUCCESS_FETCH_CATEGORIES";
export const ERROR_FETCH_CATEGORIES = "redux/auth/ERROR_FETCH_CATEGORIES";
